/**  sidebar */
export const SET_SIDEBAR_SELECTED_DATE = 'SET_SIDEBAR_SELECTED_DATE';
export const SET_SIDEBAR_ACTIVE_DATE = 'SET_SIDEBAR_ACTIVE_DATE';

/* status */
export const SET_STATUS_TODAY = 'SET_STATUS_TODAY';
export const SET_STATUS_ACTIVE_DATE = 'SET_STATUS_ACTIVE_DATE';
export const SET_STATUS_SELECTED_DATE = 'SET_STATUS_SELECTED_DATE';
export const RESET_STATUS_DATES = 'RESET_STATUS_DATES';

/* event */
export const CREATE_NEW_EVENT = 'CREATE_NEW_EVENT';
export const EDIT_EVENT = 'EDIT_EVENT';
export const DELETE_EVENT = 'DELETE_EVENT';
