/**  sidebar */
export const SET_SIDEBAR_CURRENT_DATE = 'SET_SIDEBAR_CURRENT_DATE';
export const SET_SIDEBAR_ACTIVE_DATE = 'SET_SIDEBAR_ACTIVE_DATE';

/* status */
export const SET_STATUS_TODAY = 'SET_STATUS_TODAY';
export const SET_STATUS_CURR_DATE = 'SET_STATUS_CURR_DATE';
export const RESET_STATUS_DATES = 'RESET_STATUS_DATES';
